name: microcloud
base: core22
assumes:
 - snapd2.59
version: git
grade: devel
source-code: https://github.com/canonical/microcloud.git
summary: Fully automated private clouds
description: |-
 Fully automated private clouds.

confinement: strict

apps:
  # Service
  daemon:
    command: commands/daemon.start
    daemon: simple
    plugs:
      - lxd
      - microceph
      - microovn
      - network
      - network-bind

  # Commands
  microcloud:
    command: commands/microcloud
    plugs:
      - network

parts:
  dqlite:
    after:
      - raft
    source: https://github.com/canonical/dqlite
    source-type: git
    source-depth: 1
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=
    stage-packages:
      - libsqlite3-0
      - libuv1
    build-packages:
      - libsqlite3-dev
      - libuv1-dev
      - pkg-config
    organize:
      usr/lib/: lib/
    prime:
      - lib/libdqlite*so*
      - lib/*/libuv*

  raft:
    source: https://github.com/canonical/raft
    source-type: git
    source-depth: 1
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=
    stage-packages:
      - libuv1
      - liblz4-1
    build-packages:
      - libuv1-dev
      - liblz4-dev
      - pkg-config
    organize:
      usr/lib/: lib/
    prime:
      - lib/libraft*so*
      - lib/*/libuv.so*
      #- lib/*/liblz4.so*  # use liblz4.so from the base snap

  microcloud:
    source: https://github.com/canonical/microcloud
    source-type: git
    source-depth: 1
    after:
      - dqlite
    build-snaps:
      - go
    plugin: nil
    override-pull: |
      craftctl default
      set -ex

      # Download the dependencies
      cd microcloud
      go get -d -v -tags=agent ./...
    override-build: |
      set -ex

      # Setup build environment
      export CGO_CFLAGS="-I${CRAFT_STAGE}/include/ -I${CRAFT_STAGE}/usr/local/include/"
      export CGO_LDFLAGS="-L${CRAFT_STAGE}/lib/ -L${CRAFT_STAGE}/usr/local/lib/"
      export CGO_LDFLAGS_ALLOW="(-Wl,-wrap,pthread_create)|(-Wl,-z,now)"

      # Build the binaries
      cd microcloud
      go build -trimpath -o "${CRAFT_PART_INSTALL}/bin/microcloud" -tags=agent ./cmd/microcloud
      go build -trimpath -o "${CRAFT_PART_INSTALL}/bin/microcloudd" -tags=agent,libsqlite3 ./cmd/microcloudd

      # Strip binaries
      strip -s "${CRAFT_PART_INSTALL}/bin/microcloud"
      strip -s "${CRAFT_PART_INSTALL}/bin/microcloudd"
    prime:
      - bin/microcloud
      - bin/microcloudd

  strip:
    after:
      - dqlite
      - raft
    plugin: nil
    override-prime: |
      set -x

      # Strip libraries
      find "${CRAFT_PRIME}"/lib -type f -exec strip -s {} +

  wrappers:
    plugin: dump
    source: snapcraft/
