#!/bin/sh
MICROCLOUD="microcloud"
if [ -x "${SNAP_COMMON}/microcloud.debug" ]; then
    MICROCLOUD="${SNAP_COMMON}/microcloud.debug"
    GOCOVERDIR="${SNAP_COMMON}/data/cover"
    export GOCOVERDIR
    mkdir -p "${GOCOVERDIR}"
fi

# Change the location of $VIMRUNTIME root to be able to define the defaults.vim file.
# This is to prevent seeing the message 'E1187: Failed to source defaults.vim'
# which is caused by not having the 'vim-runtime' package.
# Also see https://bugs.launchpad.net/ubuntu/+source/vim/+bug/1968912.
export VIMRUNTIME="/snap/microcloud/current/usr/share/vim/vim91"
export EDITOR="vim.tiny -Z --clean"

# Set feature flag environment variable based on the snap configuration
# This can be set/unset with the following commands:
# snap set microcloud feature.cluster-manager=true
# snap unset microcloud feature.cluster-manager
feature_cluster_manager="$(snapctl get feature.cluster-manager)"
if [ "${feature_cluster_manager:-"false"}" = "true" ]; then
    export FEATURE_CLUSTER_MANAGER=true
fi

# Run the CLI from an accessible directory which allows reads.
# When launching VIM it tries to access the $PWD regardless of the --clean setting.
cd "$SNAP_USER_DATA"
exec "${MICROCLOUD}" --state-dir "${SNAP_COMMON}/state" "$@"
